### ISSUE TITLE
UART: INIT FAILED error (also REINIT)

### ISSUE THREAD

**Issue by hpux735** [androbi-com/LoRa-E5-Mini-EndNode#3]
Hi there!

First, thanks so much for doing this repo the Seeed studio ones seem to just not work :(  

I've gotten yours building and loading on my board, but there's an issue I'm seeing in what appears to be initPMS.  Basically, once the initial boot print-out of EUIs and keys are printed, it's just `UART: REINIT FAILED` after a first `INIT FAILED`.  Also, it seems like AT commands aren't working.

Have you seen this before?  Do you have any ideas?

Thanks!

**Comment by androbi-com** [comment]
Hi @hpux735, this is the driver for the particle sensor that I had connected to the board. (PMS = Particle Measuring System). I have on my TODO list to make this code optional with a #define, but the last commit has the code activated, I am sorry. You might try going back 2 commits: https://github.com/androbi-com/LoRa-E5-Mini-EndNode/commits/main using the one just before "add air quality usart", this one only has the AHT20 temperature sensor code. Let me know if this gets you going!

**Comment by hpux735** [comment]
LOL!  That makes sense.  I'll try that out and let you know :)

**Comment by androbi-com** [comment]
I have commited a version with the AHT20 and PMS sensor readings disabled, but I could not yet test if it works. The idea is to transmit just some random values if you don't have sensors attached. I also have updated the README to explain this a bit more.

**Comment by hpux735** [comment]
`###### = JOINED = OTAA =====================`

WOOO-HOOOO!  🎉   

Thank you so much.  This is great!
