### ISSUE TITLE
Target MCU

### ISSUE THREAD

**Issue by WeSpeakEnglish** [androbi-com/LoRa-E5-Mini-EndNode#7]
Hi,
as I know  LoRa-E5-Mini module is based on STM32WLE5JC 
In LoRa-E5-Mini-EndNode.ioc I see  on str.121:
Mcu.Name=STM32WL55JCIx 
They are compatible in this app?

**Comment by androbi-com** [comment]
Yes they should. The difference is mainly that the 55 is dual core, but this feature is not used here.

**Comment by androbi-com** [comment]
No more comments, closing this issue.
