### ISSUE TITLE
Compile issue

### ISSUE THREAD

**Issue by Zeddy-** [androbi-com/LoRa-E5-Mini-EndNode#8]
Hi,

just opened the project and tried compiling after enabling the I2C 
![image](https://user-images.githubusercontent.com/1147662/169297198-b6e782fa-079e-46cb-9e8b-af792dd8cd4b.png)

c:\st\stm32cubeide_1.9.0\stm32cubeide\plugins\com.st.stm32cube.ide.mcu.externaltools.gnu-tools-for-stm32.10.3-2021.10.win32_1.0.0.202111181127\tools\arm-none-eabi\bin\ld.exe: ./Core/Src/main.o:C:/Users/melli/Downloads/LoRa-E5-Mini-EndNode-I2C/LoRa-E5-Mini-EndNode-main/Core/Inc/aht20.h:28: multiple definition of `aTxBuffer'; ./Core/Src/aht20.o:C:/Users/melli/Downloads/LoRa-E5-Mini-EndNode-I2C/LoRa-E5-Mini-EndNode-main/Core/Inc/aht20.h:28: first defined here

**Comment by androbi-com** [comment]
You should be able to resolve this by moving the declarations of aTxBuffer and aRxBuffer from aht20.h to aht20.c.

**Comment by androbi-com** [comment]
closing issue as no feedback
